FROM apache/airflow:2.8.1

USER root

# ติดตั้ง Java
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        default-jdk \
        gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH=$PATH:$JAVA_HOME/bin

USER airflow

COPY requirements.txt /requirements.txt

RUN pip install --no-cache-dir \
    --index-url https://pypi.org/simple/ \
    -r /requirements.txt

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        default-jdk \
        gcc \
        git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*